Lab4
progito/ITL pull request #6
Opened 2024-11-10 20:42 UTC by Akil12312

2024-11-10 20:44 UTC, Akil12312 commented
![depositphotos_28708655-stock-photo-oh-no](https://github.com/user-attachments/assets/98f16b06-1fd2-423a-82c2-094d2522d579)

2024-11-10 20:46 UTC, Akil12312 commented
![Uploading ff.jpeg…]()

2024-11-10 20:47 UTC, Akil12312 commented
![ff](https://github.com/user-attachments/assets/3ac2a69d-9b64-4e9f-8f64-cca402d5fb12)

2024-11-10 21:22 UTC, progito requested changes
Думаю пока хватит тебе исправлений... 

![image](https://github.com/user-attachments/assets/c76aee40-a345-4e9f-8c24-c3fe537ebf02)

2024-11-10 21:22 UTC, progito commented on part1/task1.py
> +dir_name = input("Enter the directory name: ")
`if __name__ == '__main__':` не наблюдаю..

2024-11-10 21:22 UTC, progito commented on part1/task2.py
> +number = int(input("Enter a non-negative integer: "))
аналогично `if __name__ == '__main__':`

2024-11-10 21:22 UTC, progito commented on part1/task2.py
> +    squar = math.sqrt(number)
squar? 🧐 звучит как блевота шрека.. было бы логичным именовать в sqrt_value хотя бы

2024-11-10 21:22 UTC, progito commented on part1/task2.py
> +print(f"The square root of {number} is {squar}")
записать одним принтом

2024-11-10 21:22 UTC, progito commented on part1/task3.py
> +directory = 'numbers_directory'
`if __name__ == '__main__'`

2024-11-10 21:22 UTC, progito commented on part1/task3.py
> +import random
согласно правилам PEP

`рекомендуется следовать алфавитному порядку`

![image](https://github.com/user-attachments/assets/5d5d5bdb-554a-4520-937e-a5c6b86269a9)

2024-11-10 21:22 UTC, progito commented on part1/task3.py
> +filename = 'numbers.txt'
этот адский кусок кода сделать через словарь

```python
DATA = {
    'filename': 'numbers.txt',
....
}
```

2024-11-10 21:22 UTC, progito commented on part1/task3.py
> +
добавить отступ (согласно PEP)

2024-11-10 21:22 UTC, progito commented on part1/task2.py
> +
добавить отступ (согласно PEP)

2024-11-10 21:22 UTC, progito commented on part1/task1.py
> +
добавить отступ (согласно PEP)

2024-11-10 21:22 UTC, progito commented on part1/task4.py
> +
добавить отступ (согласно PEP)

2024-11-10 21:22 UTC, progito commented on part1/task4.py
> +user_data = {
а тут значит ты решил словарь запилить) 

переименовать его в USER_DATA

2024-11-10 21:22 UTC, progito commented on part1/task4.py
> +directory_name = "user_info_directory"
а че кента в словарь забыл добавить?

2024-11-10 21:22 UTC, progito commented on part1/task4.py
> +user_data = {
`if __name__ == '__main__'`

2024-11-10 21:22 UTC, progito commented on part1/task5.py
> +user_input = input("Please enter a string: ")
`if __name__ == '__main__'`

2024-11-10 21:22 UTC, progito commented on part1/task6.py
> +
`if __name__ == '__main__'`

2024-11-10 21:22 UTC, progito commented on part2/task1.py
> +
`if __name__ == '__main__'`

2024-11-10 21:22 UTC, progito commented on part2/task2.py
> +
`if __name__ == '__main__'`

2024-11-10 21:22 UTC, progito commented on part2/task3.py
> +
`if __name__ == '__main__'`

2024-11-10 21:22 UTC, progito commented on part2/task4.py
> +plot()
`if __name__ == '__main__'`

2024-11-10 21:22 UTC, progito commented on part2/task4.py
> +    """
плохой docstring

общий шаблон такой:

```python
"""
функция делает то то...
:param a: переменная a для ...
:param b: переменная b для ...
:return: ...
"""
```

2024-11-10 21:22 UTC, progito commented on part2/task3.py
> +    """
аналогично плохой docstring

2024-11-10 21:22 UTC, progito commented on part2/task2.py
> +    """
аналогично плохой docstring

2024-11-10 21:22 UTC, progito commented on part2/task1.py
> +    """
аналогично плохой docstring

2024-11-10 21:22 UTC, progito commented on part1/task6.py
> +    """
аналогично плохой docstring

2024-11-10 21:22 UTC, progito commented on part1/task5.py
> +def find_a(text: str) -> list:
переименовать в get_all_words_with_a

2024-11-10 21:22 UTC, progito commented on part1/task6.py
> +
отступ

2024-11-10 21:22 UTC, progito commented on part2/task1.py
> +
отступ

2024-11-10 21:22 UTC, progito commented on part2/task2.py
> +
отступ

2024-11-10 21:22 UTC, progito commented on part2/task3.py
> +
отступ

2024-11-10 21:22 UTC, progito commented on part2/task4.py
> +
отступ

2024-11-10 21:22 UTC, progito commented on part2/task4.py
> +    plt.hist(data, bins=30, edgecolor='black', color='skyblue', alpha=0.7 )
нарушение PEP

отступы вокруг операторов

2024-11-10 21:22 UTC, progito commented on part2/task3.py
> +    plt.plot(x, y, label='y = x^2', color='b')
нарушение PEP отступы вокруг операторов надо накатить тут

2024-11-10 21:22 UTC, progito commented on part2/task2.py
> +    print(f"Matrix:\n{matrix}")
в один print сделай

2024-11-10 21:22 UTC, progito commented on part2/task1.py
> +    random_numbers = np.random.rand(10)
че бы тут не использовать множественное присваивание

2024-11-11 09:38 UTC, progito requested changes
требуются исправления по коду...

2024-11-11 09:38 UTC, progito commented on part1/task1.py
> +    return file_path
отступ

2024-11-11 09:38 UTC, progito commented on part1/task2.py
> +    return sqrt_value, factorial
отступ

2024-11-11 09:38 UTC, progito commented on part1/task3.py
> +    return file_path
отступ

2024-11-11 09:38 UTC, progito commented on part1/task4.py
> +if __name__ == '__main__'
отступ

2024-11-11 09:38 UTC, progito commented on part1/task4.py
> +user_data = {
user_data переименовать в USER_DATA

2024-11-11 09:38 UTC, progito commented on part1/task5.py
> +if __name__ == '__main__'
отступ

2024-11-11 09:38 UTC, progito commented on part2/task1.py
отступ

2024-11-11 09:38 UTC, progito commented on part2/task1.py
> +    print(f"Standard deviation: {std_deviation}")
отступ

2024-11-11 09:38 UTC, progito commented on part2/task2.py
> +
отступ

2024-11-11 09:38 UTC, progito commented on part2/task2.py
> +if __name__ == '__main__':
отступ

2024-11-11 09:38 UTC, progito commented on part2/task3.py
> +if __name__ == '__main__':
отступ

2024-11-11 09:38 UTC, progito commented on part2/task4.py
> +if __name__ == '__main__':
отступ

2024-11-11 09:38 UTC, progito commented on part2/task3.py
> +    plt.plot(x, y, label = 'y = x ^ 2', color = 'b')
сделать в `label = 'y=x^2'`

2024-11-11 09:38 UTC, progito commented on part1/task5.py
> +    words = re.findall(r'\b[aA]\w*', text)
сразу `return re.findall(r'\b[aA]\w*', text)`

2024-11-11 09:53 UTC, progito requested changes
почти верно...

2024-11-11 09:53 UTC, progito commented on part1/task3.py
> +import random
по алфавиту вниз

2024-11-11 09:53 UTC, progito commented on part1/task4.py
> +USER_DATA = {
вылетело из if...

2024-11-11 09:53 UTC, progito commented on part1/task5.py
> +user_input = input("Please enter a string: ")
аналогично вылетело из if

2024-11-11 09:53 UTC, progito commented on part2/task1.py
отступ тут

2024-11-11 09:53 UTC, progito commented on part2/task1.py
> +if __name__ == '__main__':
отступ тут

2024-11-11 09:53 UTC, progito commented on part2/task2.py
> +if __name__ == '__main__':
отступ тут

2024-11-11 09:53 UTC, progito commented on part2/task3.py
> +if __name__ == '__main__':
отступ тут

2024-11-11 09:53 UTC, progito commented on part2/task4.py
> +if __name__ == '__main__':
отступ тут

2024-11-11 09:59 UTC, progito requested changes
почти )

2024-11-11 09:59 UTC, progito commented on part1/task4.py
> +file_path = save_user_info(USER_DATA)
а кентов что ж забыл в if?

2024-11-11 09:59 UTC, progito commented on part1/task6.py
> +display_time()
в if

2024-11-11 10:06 UTC, progito approved these changes
Ты смог это осилить!

Что-ж ЗЕВС сказал этот код можно зачесть, БОГИ Греции тебя услышали!

ЗАЧТЕНО!

![image](https://github.com/user-attachments/assets/528793ae-9431-4cba-9f62-7febc5343c1e)

2024-11-11 10:43 UTC, closed without merging